const indicator_name_parameter_map = {
    'Dödsfall på grund av covid-19': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': 'Hela 2020',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+ år'
        ],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': 'Hela 2020',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['0-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+ år'
        ],
        'table_Tidsperiod': 'Hela 2020',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+ år'
        ],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Slutenvård med covid-19': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': 'Hela 2020',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+ år'
        ],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': 'Hela 2020',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['0-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+ år'
        ],
        'table_Tidsperiod': 'Hela 2020',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+ år'
        ],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Slutenvårdstillfällen': {
        'indikator_category_selection': 'Geriatrik',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-12 år',
            '13-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+',
            '80+ år'
        ],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['0-12 år',
            '13-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+',
            '80+ år'
        ],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-12 år',
            '13-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+',
            '80+ år'
        ],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Födelseland': {
        'indikator_category_selection': 'Annat land',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Familjetyp': {
        'indikator_category_selection': 'Ensamstående med hemmaboende barn',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Åldersgrupper': {
        'indikator_category_selection': '0-6 år',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['Se indikatorn'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['Se indikatorn'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Se indikatorn'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Öppenvårdsbesök': {
        'indikator_category_selection': 'Primärvård',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-12 år',
            '13-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+',
            '80+ år'
        ],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['0-12 år',
            '13-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+',
            '80+ år'
        ],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-12 år',
            '13-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+',
            '80+ år'
        ],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Depression och ångest': {
        'indikator_category_selection': 'Vårdkontakter depression/ångest',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-24 år', '25-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-24 år', '25-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-24 år', '25-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Bröstcancer': {
        'indikator_category_selection': 'Bröstcancer',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Kvinnor'],
        'karta_Åldersgrupp': ['0-54 år', '55+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor'],
        'linje_Åldersgrupp': ['0-54 år', '55+ år'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-54 år', '55+ år'],
        'tabel_Kön': ['Kvinnor']
    },
    'Förväntad medellivslängd': {
        'indikator_category_selection': 'Medellivslängd',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Samtliga'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Samtliga'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Samtliga'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Samtliga']
    },
    'Prostatacancer': {
        'indikator_category_selection': 'Prostatacancer',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Män'],
        'karta_Åldersgrupp': ['0-54 år', '55+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Män'],
        'linje_Åldersgrupp': ['0-54 år', '55+ år'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-54 år', '55+ år'],
        'tabel_Kön': ['Män']
    },
    'Lungcancer': {
        'indikator_category_selection': 'Lungcancer',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-54 år', '55+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['0-54 år', '55+ år'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-54 år', '55+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Tjock- och ändtarmscancer ': {
        'indikator_category_selection': 'Kolorektalcancer',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-54 år', '55+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['0-54 år', '55+ år'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-54 år', '55+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Anmälda våldsbrott': {
        'indikator_category_selection': 'Anmälda brott mot person',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Samtliga'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Samtliga'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Samtliga'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Samtliga']
    },
    'Utbildningsnivå': {
        'indikator_category_selection': 'Eftergymnasial',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['25-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['25-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['25-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Vaccinationstäckning MPR': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Samtliga'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Samtliga'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Samtliga'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Samtliga']
    },
    'Kariesfria 3-åringar': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Samtliga'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Samtliga'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Samtliga'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Samtliga']
    },
    'Exponering för tobaksrök vid 8 månaders ålder': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Samtliga'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Samtliga'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Samtliga'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Samtliga']
    },
    'Övervikt och fetma 4-åringar': {
        'indikator_category_selection': 'Fetma ',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Kvinnor', 'Män', 'Samtliga'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män', 'Samtliga'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män', 'Samtliga'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Kvinnor', 'Män', 'Samtliga']
    },
    'Amning vid 4 månaders ålder': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2019',
        'karta_Kön': ['Samtliga'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Samtliga'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Samtliga'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Samtliga']
    },
    'Övervikt och fetma': {
        'indikator_category_selection': 'Fetma',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Avstått vård på grund av dålig ekonomi': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Avstått läkemedel på grund av dålig ekonomi': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Sömnsvårigheter': {
        'indikator_category_selection': 'Lätta besvär',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Diabetes': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Begränsade sjukdom': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Huvudvärk eller migrän': {
        'indikator_category_selection': 'Lätta besvär',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Självskattad hälsa': {
        'indikator_category_selection': 'Någorlunda, dålig, mycket dålig',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Ryggsmärta': {
        'indikator_category_selection': 'Lätta besvär',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Tandhälsa': {
        'indikator_category_selection': 'Varken bra eller dålig, dålig, mycket dålig',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Nacksmärta': {
        'indikator_category_selection': 'Lätta besvär',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Riskbruk alkohol': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Ekonomiskt bistånd': {
        'indikator_category_selection': 'Ekonomiskt bistånd högst 6 mån',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['25-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['25-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['25-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Ekonomiska svårigheter': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Utsatthet för hot och våld': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Huvudsaklig sysselsättning': {
        'indikator_category_selection': 'Arbete',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['25-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['25-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['25-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Självmordstankar': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Tillit till andra människor': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Röstande i kommunval': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Samtliga'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Samtliga'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Samtliga'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Samtliga']
    },
    'Självmordsförsök': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Psykisk ohälsa': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Trafikbuller i bostad': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Tillit till institutioner': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Oro för att förlora sitt arbete': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Hjälp med personlig omvårdnad': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Hjälp med hushållssysslor': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Hjälp med att ta sig fram utomhus': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Otillräcklig hjälp i vardagslivet': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Nedsatt hörsel': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Fallolyckor': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Fallolyckor med påverkan på vardagslivet': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Inkomstnivå': {
        'indikator_category_selection': 'Högst inkomst',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Användning av narkotikaklassificerade läkemedel (senaste året)': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Användning av hasch eller marijuana (senaste året)': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Användning av annan narkotika än hasch eller marijana (senaste året)': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Snusar dagligen': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Röker dagligen': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Ensamhet': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Högt intag läsk, saft, sötade drycker': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Lågt intag frukt': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Fysisk aktivitet': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Riskabla spelvanor': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Lågt intag grönsaker': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Luftförorening på jobbet': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Våtarbete': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Boendeform': {
        'indikator_category_selection': 'Bostadsrätt',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Buller på jobbet': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Spänd arbetssituation': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Anmälan socialtjänst': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Samtliga'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Samtliga'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Samtliga'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Samtliga']
    },
    'Vibrationer på jobbet': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Fysiskt tungt arbete': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2018',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Social isolering': {
        'indikator_category_selection': 'Ej valbart',
        'karta_Tidsperiod': '2014',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2014',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2014',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Ohälsotal': {
        'indikator_category_selection': 'Ohälsotal',
        'karta_Tidsperiod': '2005',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['20-34 år', '35-49 år', '50-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2005',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Åldersgrupp': ['20-34 år', '35-49 år', '50-64 år'],
        'table_Tidsperiod': '2005',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['20-34 år', '35-49 år', '50-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    }
};
const indicator_init_map = {
    'Äldre': {
        indikator_group_selection: "Äldre",
        indikator_name_selection: "Fallolyckor",
        indikator_category_selection: "Ej valbart",
        karta_Tidsperiod: "2018",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: "65+ år",
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2018",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: "65+ år",
        table_Tidsperiod: "2018",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: "65+ år",
        tabel_Kön: ["Kvinnor", "Män"]
    },
    'Levnadsvanor': {
        indikator_group_selection: "Levnadsvanor",
        indikator_name_selection: "Använt annan narkotika än hasch eller marijana -senaste året",
        indikator_category_selection: "Ej valbart",
        karta_Tidsperiod: "2018",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2018",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        table_Tidsperiod: "2018",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        tabel_Kön: ["Kvinnor", "Män"]
    },
    'Hälsa och sjukdom': {
        indikator_group_selection: "Hälsa och sjukdom",
        indikator_name_selection: "Begränsade sjukdom",
        indikator_category_selection: "Ej valbart",
        karta_Tidsperiod: "2018",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2018",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        table_Tidsperiod: "2018",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        tabel_Kön: ["Kvinnor", "Män"]
    },
    'Hälso- och sjukvård': {
        indikator_group_selection: "Hälso- och sjukvård",
        indikator_name_selection: "Avstått läkemedel på grund av dålig ekonomi",
        indikator_category_selection: "Ej valbart",
        karta_Tidsperiod: "2018",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2018",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        table_Tidsperiod: "2018",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        tabel_Kön: ["Kvinnor", "Män"]
    },
    'Covid-19': {
        indikator_group_selection: "Covid-19",
        indikator_name_selection: "Dödsfall på grund av covid-19",
        indikator_category_selection: "Ej valbart",
        karta_Tidsperiod: "Hela 2020",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: ["0-24 år", "25-44 år", "45-64 år", "65-79 år", "80+ år"],
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "Hela 2020",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: ["0-24 år", "25-44 år", "45-64 år", "65-79 år", "80+ år"],
        table_Tidsperiod: "Hela 2020",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: ["0-24 år", "25-44 år", "45-64 år", "65-79 år", "80+ år"],
        tabel_Kön: ["Kvinnor", "Män"]
    },
    'Psykisk hälsa': {
        indikator_group_selection: "Psykisk hälsa",
        indikator_name_selection: "Ensamhet",
        indikator_category_selection: "Ej valbart",
        karta_Tidsperiod: "2018",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2018",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        table_Tidsperiod: "2018",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        tabel_Kön: ["Kvinnor", "Män"]
    },
    'Sociala relationer, demokrati och miljö': {
        indikator_group_selection: "Sociala relationer, demokrati och miljö",
        indikator_name_selection: "Anmälda våldsbrott",
        indikator_category_selection: "Anmälda brott mot person",
        karta_Tidsperiod: "2019",
        karta_Kön: "Samtliga",
        karta_Åldersgrupp: "Samtliga",
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2019",
        stapel_Kön: "Samtliga",
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: "Samtliga",
        linje_Åldersgrupp: "Samtliga",
        table_Tidsperiod: "2019",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: "Samtliga",
        tabel_Kön: "Samtliga"
    },
    'Utbildning, sysselsättning och inkomst': {
        indikator_group_selection: "Utbildning, sysselsättning och inkomst",
        indikator_name_selection: "Ekonomiska svårigheter",
        indikator_category_selection: "Ej valbart",
        karta_Tidsperiod: "2018",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2018",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        table_Tidsperiod: "2018",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        tabel_Kön: ["Kvinnor", "Män"]
    },
    'Arbetsmiljö': {
        indikator_group_selection: "Arbetsmiljö",
        indikator_name_selection: "Buller på jobbet",
        indikator_category_selection: "Ej valbart",
        karta_Tidsperiod: "2018",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: ["16-44 år", "45-64 år"],
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2018",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: ["16-44 år", "45-64 år"],
        table_Tidsperiod: "2018",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: ["16-44 år", "45-64 år"],
        tabel_Kön: ["Kvinnor", "Män"]
    },
    'Demografi': {
        indikator_group_selection: "Demografi",
        indikator_name_selection: "Åldersgrupper",
        indikator_category_selection: ["0-6 år", "7-12 år", "13-19 år"],
        karta_Tidsperiod: "2019",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: "Se indikatorn",
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2019",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: "Se indikatorn",
        table_Tidsperiod: "2019",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: "Se indikatorn",
        tabel_Kön: ["Kvinnor", "Män"]
    },
    'Barn': {
        indikator_group_selection: "Barn",
        indikator_name_selection: "Amning vid 4 månaders ålder",
        indikator_category_selection: "Ej valbart",
        karta_Tidsperiod: "2019",
        karta_Kön: "Samtliga",
        karta_Åldersgrupp: "Samtliga",
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2019",
        stapel_Kön: "Samtliga",
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: "Samtliga",
        linje_Åldersgrupp: "Samtliga",
        table_Tidsperiod: "2019",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: "Samtliga",
        tabel_Kön: "Samtliga"
    },
}
const id_indicaotr = {
    '138423': 'Arbetsmiljö',
    '138425': 'Barn',
    '138427': 'Covid-19',
    '138424': 'Demografi',
    '138391': 'Hälsa och sjukdom',
    '138415': 'Hälso- och sjukvård',
    '138365': 'Levnadsvanor',
    '138419': 'Psykisk hälsa',
    '138421': 'Sociala relationer, demokrati och miljö',
    '138422': 'Utbildning, sysselsättning och inkomst',
    '138426': 'Äldre'
}