const indicator_name_parameter_map = {
    'Dödsfall på grund av covid-19': {
        'indikator_group': 'Covid-19',
        'indikator_name': 'Dödsfall på grund av covid-19',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+ år'
        ],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': 'Hela 2020',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['0-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+ år'
        ],
        'table_Tidsperiod': 'Hela 2020',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+ år'
        ],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Slutenvård med covid-19': {
        'indikator_group': 'Covid-19',
        'indikator_name': 'Slutenvård med covid-19',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+ år'
        ],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': 'Hela 2020',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['0-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+ år'
        ],
        'table_Tidsperiod': 'Hela 2020',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+ år'
        ],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Öppenvårdsbesök': {
        'indikator_group': 'Hälso- och sjukvård',
        'indikator_name': 'Öppenvårdsbesök',
        'indikator_category': 'Primärvård',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-12 år',
            '13-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+',
            '80+ år'
        ],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['0-12 år',
            '13-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+',
            '80+ år'
        ],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-12 år',
            '13-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+',
            '80+ år'
        ],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Födelseland': {
        'indikator_group': 'Demografi',
        'indikator_name': 'Födelseland',
        'indikator_category': 'Europa',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Depression och ångest': {
        'indikator_group': 'Psykisk hälsa',
        'indikator_name': 'Depression och ångest',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-24 år', '25-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-24 år', '25-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-24 år', '25-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Bröstcancer': {
        'indikator_group': 'Hälsa och sjukdom',
        'indikator_name': 'Bröstcancer',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor'],
        'karta_Åldersgrupp': ['0-54 år', '55+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor'],
        'linje_Kön': ['Kvinnor'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['0-54 år', '55+ år'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-54 år', '55+ år'],
        'tabel_Kön': ['Kvinnor']
    },
    'Utbildningsnivå': {
        'indikator_group': 'Utbildning, sysselsättning och inkomst',
        'indikator_name': 'Utbildningsnivå',
        'indikator_category': 'Eftergymnasial',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['25-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['25-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['25-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Lungcancer': {
        'indikator_group': 'Hälsa och sjukdom',
        'indikator_name': 'Lungcancer',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-54 år', '55+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['0-54 år', '55+ år'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-54 år', '55+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Familjetyp': {
        'indikator_group': 'Demografi',
        'indikator_name': 'Familjetyp',
        'indikator_category': 'Ensamstående med hemmaboende barn',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Slutenvårdstillfällen': {
        'indikator_group': 'Hälso- och sjukvård',
        'indikator_name': 'Slutenvårdstillfällen',
        'indikator_category': 'Geriatrik',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-12 år',
            '13-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+',
            '80+ år'
        ],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['0-12 år',
            '13-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+',
            '80+ år'
        ],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-12 år',
            '13-24 år',
            '25-44 år',
            '45-64 år',
            '65-79 år',
            '80+',
            '80+ år'
        ],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Anmälda våldsbrott': {
        'indikator_group': 'Sociala relationer, demokrati och miljö',
        'indikator_name': 'Anmälda våldsbrott',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Samtliga'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Samtliga'],
        'linje_Kön': ['Samtliga'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Samtliga']
    },
    'Åldersgrupper': {
        'indikator_group': 'Demografi',
        'indikator_name': 'Åldersgrupper',
        'indikator_category': '0-6 år',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['Se indikatorn'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['Se indikatorn'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Se indikatorn'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Prostatacancer': {
        'indikator_group': 'Hälsa och sjukdom',
        'indikator_name': 'Prostatacancer',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Män'],
        'karta_Åldersgrupp': ['0-54 år', '55+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Män'],
        'linje_Kön': ['Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['0-54 år', '55+ år'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-54 år', '55+ år'],
        'tabel_Kön': ['Män']
    },
    'Tjock- och ändtarmscancer ': {
        'indikator_group': 'Hälsa och sjukdom',
        'indikator_name': 'Tjock- och ändtarmscancer ',
        'indikator_category': 'Kolorektalcancer',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-54 år', '55+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['0-54 år', '55+ år'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-54 år', '55+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Övervikt och fetma 4-åringar': {
        'indikator_group': 'Barn',
        'indikator_name': 'Övervikt och fetma 4-åringar',
        'indikator_category': 'Fetma ',
        'karta_Kön': ['Flickar', 'Pojkar'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Flickar', 'Pojkar'],
        'linje_Kön': ['Flickar', 'Pojkar'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Flickar', 'Pojkar']
    },
    'Amning vid 4 månaders ålder': {
        'indikator_group': 'Barn',
        'indikator_name': 'Amning vid 4 månaders ålder',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Samtliga'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Samtliga'],
        'linje_Kön': ['Samtliga'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Samtliga']
    },
    'Kariesfria 3-åringar': {
        'indikator_group': 'Barn',
        'indikator_name': 'Kariesfria 3-åringar',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Samtliga'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Samtliga'],
        'linje_Kön': ['Samtliga'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Samtliga']
    },
    'Exponering för tobaksrök vid 8 månaders ålder': {
        'indikator_group': 'Barn',
        'indikator_name': 'Exponering för tobaksrök vid 8 månaders ålder',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Samtliga'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Samtliga'],
        'linje_Kön': ['Samtliga'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Samtliga']
    },
    'Vaccinationstäckning MPR': {
        'indikator_group': 'Barn',
        'indikator_name': 'Vaccinationstäckning MPR',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Samtliga'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Samtliga'],
        'linje_Kön': ['Samtliga'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Samtliga']
    },
    'Förväntad medellivslängd': {
        'indikator_group': 'Hälsa och sjukdom',
        'indikator_name': 'Förväntad medellivslängd',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Samtliga'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2019',
        'stapel_Kön': ['Samtliga'],
        'linje_Kön': ['Samtliga'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2019',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Samtliga']
    },
    'Diabetes': {
        'indikator_group': 'Hälsa och sjukdom',
        'indikator_name': 'Diabetes',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Självmordstankar': {
        'indikator_group': 'Psykisk hälsa',
        'indikator_name': 'Självmordstankar',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Trafikbuller i bostad': {
        'indikator_group': 'Sociala relationer, demokrati och miljö',
        'indikator_name': 'Trafikbuller i bostad',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Ekonomiska svårigheter': {
        'indikator_group': 'Utbildning, sysselsättning och inkomst',
        'indikator_name': 'Ekonomiska svårigheter',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Utsatthet för hot och våld': {
        'indikator_group': 'Sociala relationer, demokrati och miljö',
        'indikator_name': 'Utsatthet för hot och våld',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Ekonomiskt bistånd': {
        'indikator_group': 'Utbildning, sysselsättning och inkomst',
        'indikator_name': 'Ekonomiskt bistånd',
        'indikator_category': 'Ekonomiskt bistånd högst 6 mån',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['25-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['25-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['25-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Tillit till andra människor': {
        'indikator_group': 'Sociala relationer, demokrati och miljö',
        'indikator_name': 'Tillit till andra människor',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Självmordsförsök': {
        'indikator_group': 'Psykisk hälsa',
        'indikator_name': 'Självmordsförsök',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Begränsade sjukdom': {
        'indikator_group': 'Hälsa och sjukdom',
        'indikator_name': 'Begränsade sjukdom',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Huvudvärk eller migrän': {
        'indikator_group': 'Hälsa och sjukdom',
        'indikator_name': 'Huvudvärk eller migrän',
        'indikator_category': 'Lätta besvär',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Röstande i kommunval': {
        'indikator_group': 'Sociala relationer, demokrati och miljö',
        'indikator_name': 'Röstande i kommunval',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Samtliga'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Samtliga'],
        'linje_Kön': ['Samtliga'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Samtliga']
    },
    'Tillit till institutioner': {
        'indikator_group': 'Sociala relationer, demokrati och miljö',
        'indikator_name': 'Tillit till institutioner',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Otillräcklig hjälp i vardagslivet': {
        'indikator_group': 'Äldre',
        'indikator_name': 'Otillräcklig hjälp i vardagslivet',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Inkomstnivå': {
        'indikator_group': 'Utbildning, sysselsättning och inkomst',
        'indikator_name': 'Inkomstnivå',
        'indikator_category': 'Högst inkomst',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Psykisk ohälsa': {
        'indikator_group': 'Psykisk hälsa',
        'indikator_name': 'Psykisk ohälsa',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Huvudsaklig sysselsättning': {
        'indikator_group': 'Utbildning, sysselsättning och inkomst',
        'indikator_name': 'Huvudsaklig sysselsättning',
        'indikator_category': 'Arbete',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['25-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['25-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['25-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Sömnsvårigheter': {
        'indikator_group': 'Hälsa och sjukdom',
        'indikator_name': 'Sömnsvårigheter',
        'indikator_category': 'Lätta besvär',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Övervikt och fetma': {
        'indikator_group': 'Hälsa och sjukdom',
        'indikator_name': 'Övervikt och fetma',
        'indikator_category': 'Fetma',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Avstått läkemedel på grund av dålig ekonomi': {
        'indikator_group': 'Hälso- och sjukvård',
        'indikator_name': 'Avstått läkemedel på grund av dålig ekonomi',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Avstått vård på grund av dålig ekonomi': {
        'indikator_group': 'Hälso- och sjukvård',
        'indikator_name': 'Avstått vård på grund av dålig ekonomi',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Självskattad hälsa': {
        'indikator_group': 'Hälsa och sjukdom',
        'indikator_name': 'Självskattad hälsa',
        'indikator_category': 'Någorlunda, dålig, mycket dålig',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Användning av annan narkotika än hasch eller marijuana': {
        'indikator_group': 'Levnadsvanor',
        'indikator_name': 'Användning av annan narkotika än hasch eller marijuana',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Tandhälsa': {
        'indikator_group': 'Hälsa och sjukdom',
        'indikator_name': 'Tandhälsa',
        'indikator_category': 'Varken bra eller dålig, dålig, mycket dålig',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Nacksmärta': {
        'indikator_group': 'Hälsa och sjukdom',
        'indikator_name': 'Nacksmärta',
        'indikator_category': 'Lätta besvär',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Snusar dagligen': {
        'indikator_group': 'Levnadsvanor',
        'indikator_name': 'Snusar dagligen',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Röker dagligen': {
        'indikator_group': 'Levnadsvanor',
        'indikator_name': 'Röker dagligen',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Riskbruk alkohol': {
        'indikator_group': 'Levnadsvanor',
        'indikator_name': 'Riskbruk alkohol',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Ensamhet': {
        'indikator_group': 'Psykisk hälsa',
        'indikator_name': 'Ensamhet',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Ryggsmärta': {
        'indikator_group': 'Hälsa och sjukdom',
        'indikator_name': 'Ryggsmärta',
        'indikator_category': 'Lätta besvär',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Fysisk aktivitet': {
        'indikator_group': 'Levnadsvanor',
        'indikator_name': 'Fysisk aktivitet',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Användning av narkotikaklassificerade läkemedel': {
        'indikator_group': 'Levnadsvanor',
        'indikator_name': 'Användning av narkotikaklassificerade läkemedel',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Högt intag läsk, saft, sötade drycker': {
        'indikator_group': 'Levnadsvanor',
        'indikator_name': 'Högt intag läsk, saft, sötade drycker',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Användning av hasch eller marijuana (senaste året)': {
        'indikator_group': 'Levnadsvanor',
        'indikator_name': 'Användning av hasch eller marijuana (senaste året)',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Lågt intag grönsaker': {
        'indikator_group': 'Levnadsvanor',
        'indikator_name': 'Lågt intag grönsaker',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Riskabla spelvanor': {
        'indikator_group': 'Levnadsvanor',
        'indikator_name': 'Riskabla spelvanor',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Lågt intag frukt': {
        'indikator_group': 'Levnadsvanor',
        'indikator_name': 'Lågt intag frukt',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Våtarbete': {
        'indikator_group': 'Arbetsmiljö',
        'indikator_name': 'Våtarbete',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Buller på jobbet': {
        'indikator_group': 'Arbetsmiljö',
        'indikator_name': 'Buller på jobbet',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Boendeform': {
        'indikator_group': 'Demografi',
        'indikator_name': 'Boendeform',
        'indikator_category': 'Bostadsrätt',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['0-24 år', '25-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Anmälan socialtjänst': {
        'indikator_group': 'Barn',
        'indikator_name': 'Anmälan socialtjänst',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Samtliga'],
        'karta_Åldersgrupp': ['Samtliga'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Samtliga'],
        'linje_Kön': ['Samtliga'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['Samtliga'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['Samtliga'],
        'tabel_Kön': ['Samtliga']
    },
    'Luftförorening på jobbet': {
        'indikator_group': 'Arbetsmiljö',
        'indikator_name': 'Luftförorening på jobbet',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Nedsatt hörsel': {
        'indikator_group': 'Äldre',
        'indikator_name': 'Nedsatt hörsel',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Fallolyckor med påverkan på vardagslivet': {
        'indikator_group': 'Äldre',
        'indikator_name': 'Fallolyckor med påverkan på vardagslivet',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Oro för att förlora sitt arbete': {
        'indikator_group': 'Utbildning, sysselsättning och inkomst',
        'indikator_name': 'Oro för att förlora sitt arbete',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Hjälp med att ta sig fram utomhus': {
        'indikator_group': 'Äldre',
        'indikator_name': 'Hjälp med att ta sig fram utomhus',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Vibrationer på jobbet': {
        'indikator_group': 'Arbetsmiljö',
        'indikator_name': 'Vibrationer på jobbet',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Hjälp med personlig omvårdnad': {
        'indikator_group': 'Äldre',
        'indikator_name': 'Hjälp med personlig omvårdnad',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Spänd arbetssituation': {
        'indikator_group': 'Arbetsmiljö',
        'indikator_name': 'Spänd arbetssituation',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Fysiskt tungt arbete': {
        'indikator_group': 'Arbetsmiljö',
        'indikator_name': 'Fysiskt tungt arbete',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Fallolyckor': {
        'indikator_group': 'Äldre',
        'indikator_name': 'Fallolyckor',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Hjälp med hushållssysslor': {
        'indikator_group': 'Äldre',
        'indikator_name': 'Hjälp med hushållssysslor',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2018',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['65+ år'],
        'table_Tidsperiod': '2018',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Social isolering': {
        'indikator_group': 'Sociala relationer, demokrati och miljö',
        'indikator_name': 'Social isolering',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2014',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'table_Tidsperiod': '2014',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['16-44 år', '45-64 år', '65+ år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    },
    'Ohälsodagar': {
        'indikator_group': 'Hälsa och sjukdom',
        'indikator_name': 'Ohälsodagar',
        'indikator_category': 'Ej valbart',
        'karta_Kön': ['Kvinnor', 'Män'],
        'karta_Åldersgrupp': ['20-34 år', '35-49 år', '50-64 år'],
        'stapel_Område': 'Stockholms län',
        'stapel_Tidsperiod': '2005',
        'stapel_Kön': ['Kvinnor', 'Män'],
        'linje_Kön': ['Kvinnor', 'Män'],
        'linje_Område': ['Stockholms län', 'Botkyrka'],
        'linje_Åldersgrupp': ['20-34 år', '35-49 år', '50-64 år'],
        'table_Tidsperiod': '2005',
        'table_Område': 'Stockholms län',
        'tabel_Åldersgrupp': ['20-34 år', '35-49 år', '50-64 år'],
        'tabel_Kön': ['Kvinnor', 'Män']
    }
}
const indicator_init_map = {
    "Äldre": {
        indikator_group: "Äldre",
        indikator_name: "Fallolyckor",
        indikator_category: "Ej valbart",
        karta_Tidsperiod: "2018",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: "65+ år",
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2018",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: "65+ år",
        table_Tidsperiod: "2018",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: "65+ år",
        tabel_Kön: ["Kvinnor", "Män"]
    },
    "Levnadsvanor": {
        indikator_group: "Levnadsvanor",
        indikator_name: "Använt annan narkotika än hasch eller marijana -senaste året",
        indikator_category: "Ej valbart",
        karta_Tidsperiod: "2018",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2018",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        table_Tidsperiod: "2018",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        tabel_Kön: ["Kvinnor", "Män"]
    },
    "Hälsa och sjukdom": {
        indikator_group: "Hälsa och sjukdom",
        indikator_name: "Begränsade sjukdom",
        indikator_category: "Ej valbart",
        karta_Tidsperiod: "2018",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2018",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        table_Tidsperiod: "2018",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        tabel_Kön: ["Kvinnor", "Män"]
    },
    "Hälso- och sjukvård": {
        indikator_group: "Hälso- och sjukvård",
        indikator_name: "Avstått läkemedel på grund av dålig ekonomi",
        indikator_category: "Ej valbart",
        karta_Tidsperiod: "2018",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2018",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        table_Tidsperiod: "2018",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        tabel_Kön: ["Kvinnor", "Män"]
    },
    "Covid-19": {
        indikator_group: "Covid-19",
        indikator_name: "Dödsfall på grund av covid-19",
        indikator_category: "Ej valbart",
        karta_Tidsperiod: "Hela 2020",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: ["0-24 år", "25-44 år", "45-64 år", "65-79 år", "80+ år"],
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "Hela 2020",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: ["0-24 år", "25-44 år", "45-64 år", "65-79 år", "80+ år"],
        table_Tidsperiod: "Hela 2020",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: ["0-24 år", "25-44 år", "45-64 år", "65-79 år", "80+ år"],
        tabel_Kön: ["Kvinnor", "Män"]
    },
    "Psykisk hälsa": {
        indikator_group: "Psykisk hälsa",
        indikator_name: "Ensamhet",
        indikator_category: "Ej valbart",
        karta_Tidsperiod: "2018",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2018",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        table_Tidsperiod: "2018",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        tabel_Kön: ["Kvinnor", "Män"]
    },
    "Sociala relationer, demokrati och miljö": {
        indikator_group: "Sociala relationer, demokrati och miljö",
        indikator_name: "Anmälda våldsbrott",
        indikator_category: "Anmälda brott mot person",
        karta_Tidsperiod: "2019",
        karta_Kön: "Samtliga",
        karta_Åldersgrupp: "Samtliga",
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2019",
        stapel_Kön: "Samtliga",
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: "Samtliga",
        linje_Åldersgrupp: "Samtliga",
        table_Tidsperiod: "2019",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: "Samtliga",
        tabel_Kön: "Samtliga"
    },
    "Utbildning, sysselsättning och inkomst": {
        indikator_group: "Utbildning, sysselsättning och inkomst",
        indikator_name: "Ekonomiska svårigheter",
        indikator_category: "Ej valbart",
        karta_Tidsperiod: "2018",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2018",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        table_Tidsperiod: "2018",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: ["16-44 år", "45-64 år", "65+ år"],
        tabel_Kön: ["Kvinnor", "Män"]
    },
    "Arbetsmiljö": {
        indikator_group: "Arbetsmiljö",
        indikator_name: "Buller på jobbet",
        indikator_category: "Ej valbart",
        karta_Tidsperiod: "2018",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: ["16-44 år", "45-64 år"],
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2018",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: ["16-44 år", "45-64 år"],
        table_Tidsperiod: "2018",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: ["16-44 år", "45-64 år"],
        tabel_Kön: ["Kvinnor", "Män"]
    },
    "Demografi": {
        indikator_group: "Demografi",
        indikator_name: "Åldersgrupper",
        indikator_category: ["0-6 år", "7-12 år", "13-19 år"],
        karta_Tidsperiod: "2019",
        karta_Kön: ["Kvinnor", "Män"],
        karta_Åldersgrupp: "Se indikatorn",
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2019",
        stapel_Kön: ["Kvinnor", "Män"],
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: ["Kvinnor", "Män"],
        linje_Åldersgrupp: "Se indikatorn",
        table_Tidsperiod: "2019",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: "Se indikatorn",
        tabel_Kön: ["Kvinnor", "Män"]
    },
    "Barn": {
        indikator_group: "Barn",
        indikator_name: "Amning vid 4 månaders ålder",
        indikator_category: "Ej valbart",
        karta_Tidsperiod: "2019",
        karta_Kön: "Samtliga",
        karta_Åldersgrupp: "Samtliga",
        stapel_Område: "Stockholms län",
        stapel_Tidsperiod: "2019",
        stapel_Kön: "Samtliga",
        linje_Område: ["Stockholms län", "Botkyrka"],
        linje_Kön: "Samtliga",
        linje_Åldersgrupp: "Samtliga",
        table_Tidsperiod: "2019",
        table_Område: "Stockholms län",
        tabel_Åldersgrupp: "Samtliga",
        tabel_Kön: "Samtliga"
    },
}
const id_indicaotr = {
    "138423": "Arbetsmiljö",
    "138425": "Barn",
    "138427": "Covid-19",
    "138424": "Demografi",
    "138391": "Hälsa och sjukdom",
    "138415": "Hälso- och sjukvård",
    "138365": "Levnadsvanor",
    "138419": "Psykisk hälsa",
    "138421": "Sociala relationer, demokrati och miljö",
    "138422": "Utbildning, sysselsättning och inkomst",
    "138426": "Äldre"
}